export const BATTLE_CONFIG = {
  STAGE: {
    BASE: 1,
    MAX: 50
  },
  BOSS: {
    BASE_HEALTH: 5,
    HEALTH_EXP_GROWTH_RATE: 1.25
  },
  REWARDS: {
    BASE_EXPERIENCE_REWARD: 20,
    EXPERIENCE_REWARD_PER_STAGE: 10,
    BASE_GOLD_REWARD: 10,
    GOLD_REWARD_PER_STAGE: 2
  }
};
