export const CHARACTER_CONFIG = {
  LEVEL: {
    BASE_LEVEL: 1,
    MAX_LEVEL: 100,
    SKILL_POINTS_PER_LEVEL: 1
  },
  EXPERIENCE: {
    BASE_EXPERIENCE: 0,
    BASE_EXPERIENCE_TO_NEXT_LEVEL: 100,
    EXPERIENCE_GROWTH_RATE: 1.075
  }
};
