export const DELAYS = {
  BATTLE_RESTART_MS: 5000,
  LEVEL_UP_ANIMATION_MS: 250,
  LEVEL_UP_RESET_MS: 50,
  BOSS_RESPAWN_ANIMATION_MS: 1000,
  HERO_ATTACK_ANIMATION_MS: 260,
  HERO_CRIT_ANIMATION_MS: 320,
  HERO_MULTI_HIT_ANIMATION_MS: 380,
  HERO_CRIT_MULTI_HIT_ANIMATION_MS: 400
};
