export const ENCHANTING_CONFIG = {
  LEVEL: {
    UNENCHANTED: 0,
    BASE: 1,
    MAX: 5
  },
  COSTS: {
    ENCHANT_COST: 100,
    UPGRADE_COST_PER_LEVEL: 300,
    REROLL_COST: 200
  },
  UPGRADE: {
    STAT_MODIFIER: 1.3
  }
};
