export const GAME_CONFIG = {
  LEVEL: {
    BASE_LEVEL: 1,
    MAX_LEVEL: 100,
    SKILL_POINTS_PER_LEVEL: 1,
    BASE_EXPERIENCE: 0,
    BASE_EXPERIENCE_TO_NEXT_LEVEL: 100,
    EXPERIENCE_GROWTH_RATE: 1.075
  },
  STAGE: {
    BASE: 1,
    MAX: 2
  },
  BOSS: {
    BASE_HEALTH: 5,
    HEALTH_EXP_GROWTH_RATE: 1.25
  },
  REWARDS: {
    BASE_EXPERIENCE_REWARD: 20,
    EXPERIENCE_REWARD_PER_STAGE: 10,
    BASE_GOLD_REWARD: 10,
    GOLD_REWARD_PER_STAGE: 2
  },
  CURRENCIES: {
    GOLD: {
      STARTING_AMOUNT: 0
    }
  }
};
