export const STATS_CONFIG = {
  ATTRIBUTES: {
    STRENGTH_BASE: 1,
    INTELLIGENCE_BASE: 1,
    DEXTERITY_BASE: 1
  },
  ATTACK_POWER: {
    BASE: 1,
    ATTACK_POWER_PER_STRENGTH: 1,
    EXPONENT: 1.5
  },
  ATTACK_SPEED: {
    BASE: 1,
    ATTACK_SPEED_PER_DEXTERITY: 0.01
  },
  CHC: {
    BASE: 0.01,
    MAX: 1,
    CHC_PER_INTELLIGENCE: 0.0075
  },
  CHD: {
    BASE: 1.5
  },
  MHC: {
    BASE: 0.0,
    MAX: 0.5,
    MHC_PER_DEXTERITY: 0.005
  },
  MHD: {
    BASE: 2
  }
};
