export const DELAYS = {
  BATTLE_RESTART_MS: 5000,
  LEVEL_UP_ANIMATION_MS: 250,
  LEVEL_UP_RESET_MS: 50,
  BLEEDING_CLEAR_MS: 250,
  BOSS_RESPAWN_ANIMATION_MIN_MS: 220,
  BOSS_RESPAWN_ANIMATION_BASE_MS: 1000,
  BOSS_RESPAWN_ANIMATION_MAX_MS: 1250
};
